Lieu.create!(name:"Demeure de la Carmine ",city:" Mirepoix ",description:" 30min ",phone:" 06 70 42 11 50 ",url:" http://demeurecarmine.com",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Domaine de la Trille ",city:" Ste Foi ",description:" 35min ",phone:" 05 61 67 89 82 ",url:" http://www.domainedelatrille.com",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Domaine Thomson ",city:" Engraviès ",description:" 15min ",phone:" 05 61 60 60 20 ",url:" http://fr.domainethomson.com",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Domaine la Barre ",city:" Engravies ",description:" 15min ",phone:" 05 61 68 81 20 ",url:" http://www.chambres-hotes-ariege.com",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Gîte et chambre de Mirepoix ",city:" Mirepoix ",description:" 30min ",phone:" 06 21 01 17 95 ",url:" http://www.gites-mirepoix.com",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Auberge du Balestie ",city:" Mirepoix ",description:" 30min ",phone:" 05 61 69 58 64 ",url:" http://www.auberge-du-balestie.com",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Abbaye de Camon ",city:" Camon ",description:" 35min ",phone:" 05 61 60 31 23 ",url:" http://www.chateaudecamon.com",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Mi René ",city:" Lagarde ",description:" 25min ",phone:" 05 61 68 98 46 ",url:" http://www.ariege.com/mi-rene/",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Domaine du Hameau ",city:" St Jean d’Aiguë vive ",description:" 25min ",phone:" 05 34 14 63 65 ",url:" http://www.hameaubaylesse.com",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"L’impasse du Temps ",city:" Léran ",description:" 15min ",phone:" 05 61 01 50 02 ",url:" http://www.chezfurness.com",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"La maison Rose ",city:" Léran ",description:" 15min ",phone:" 04 68 31 05 73 ",url:" http://www.lac-de-montbel.com/fr",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Santa Colomba ",city:" Ste Colombe sur l’Hers ",description:" 20min ",phone:" 06 80 10 56 24 ",url:" http://www.santa-colomba.fr",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Aux quatre saisons ",city:" Tabre ",description:" 15min ",phone:" 05.61.01.81.14 ",url:" http://www.aux4saisons09.com",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Le Labyrinthe ",city:" Montségur (château) ",description:" 35min ",phone:" ",url:"",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Le café du Théâtre ",city:" Lavelanet ",description:" 20min ",phone:" 06 87 46 53 60",url:"",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Les Sabines ",city:" Montgaillard ",description:" 30min ",phone:"",url:"",genre:"CHAMBRE D\’HÔTES")
Lieu.create!(name:"Domaine la Barre (2 à 7 pers) ",city:" Engravies ",description:" 15min ",phone:" 05 61 68 81 20 ",url:" http://www.chambres-hotes-ariege.com",genre:"GÎTE")
Lieu.create!(name:"La maison du Roy (4 à 8 pers) ",city:" Lieurac ",description:" 5min",phone:"",url:"",genre:"GÎTE")
Lieu.create!(name:"A Roquefort les cascades (6pers) ",city:" (Piscine) ",description:" 10min",phone:"",url:"",genre:"GÎTE")
Lieu.create!(name:"La maison de roquefort ",city:" Carla de Roquefort ",description:" 5min ",phone:" 05 61 01 21 29",url:"",genre:"GÎTE")
Lieu.create!(name:"Ventenac : Marinette et Robert Comelongue (piscine) ",city:"Ventenac",description:" 5min ",phone:" 05 61 60 72 43 ",url:"",genre:"CAMPING")
Lieu.create!(name:"Hôtel les Minotiers ",city:" Mirepoix ",description:" 30min ",phone:" 05 61 69 37 36 ",url:" http://www.hotelmirepoix.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel le Commerce ",city:" Mirepoix ",description:" 30min ",phone:" 05 61 68 10 29 ",url:" http://www.le-commerce.fr",genre:"HÔTEL")
Lieu.create!(name:"Hôtel les remparts ",city:" Mirepoix ",description:" 30min ",phone:" 05 61 68 12 15 ",url:" http://www.hotelremparts.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel la maison des consuls ",city:" Mirepoix ",description:" 30min ",phone:" 05 61 68 81 81 ",url:" http://www.maisondesconsuls.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel du rélais royal ",city:" Mirepoix ",description:" 30min ",phone:" 05 61 60 19 19 ",url:"http://www.relaisroyal.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel Costes ",city:" Montségur ",description:" 35min ",phone:" 05 61 02 66 21",url:"",genre:"HÔTEL")
Lieu.create!(name:"Hôtel Couquet ",city:" Montségur ",description:" 35min ",phone:" 05 61 01 10 28 ",url:"",genre:"HÔTEL")
Lieu.create!(name:"Hôtel de France ",city:" Chalabre ",description:" 35min",phone:"",url:"",genre:"HÔTEL")
Lieu.create!(name:"Hôtel Castel d’Olmes ",city:" Laroque d’Olmes ",description:" 15min ",phone:" 05 61 01 04 58 ",url:" http://www.casteldolmes.fr",genre:"HÔTEL")
Lieu.create!(name:"Hôtel Castrum ",city:" Villeneuve d’Olmes ",description:" 25min ",phone:" 05 61 04 44 00 ",url:" http://www.lecastrum.fr",genre:"HÔTEL")
Lieu.create!(name:"Auberge la Barguillère ",city:" Saint Pierre de rivière ",description:" 35min ",phone:" 05 61 65 14 02 ",url:" http://www.barguillere.fr",genre:"HÔTEL")
Lieu.create!(name:"Auberge Léo ",city:" Foix ",description:" 30min ",phone:" 05 61 65 09 04 ",url:" http://www.leodefoix.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel Balladins ",city:" Foix ",description:" 30min ",phone:" 05 61 05 36 10 ",url:" https://www.balladins.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel Eychenne ",city:" Foix ",description:" 30min ",phone:" 05 61 04 04 50 ",url:" http://www.ariege.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel du Lac ",city:" Foix ",description:" 30min ",phone:" 05 61 65 17 17 ",url:" http://www.hoteldulac-foix.fr",genre:"HÔTEL")
Lieu.create!(name:"Hôtel Lons ",city:" Foix ",description:" 30min ",phone:" 05 34 09 28 00 ",url:" http://www.hotel-lons-foix.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel de France ",city:" Pamiers ",description:" 30min ",phone:" 05 61 60 20 88 ",url:" http://hotel-de-France-pamiers.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel de la paix ",city:" Pamiers ",description:" 30min ",phone:" 05 61 67 12 71 ",url:" http://hoteldelapaix-pamiers.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel le Roi Gourmand ",city:" Pamiers ",description:" 30min ",phone:" 05 61 60 12 12 ",url:" http://www.hotel-roigourmand09.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel Rocade ",city:" Pamiers ",description:" 30min ",phone:" 05 34 02 12 13 ",url:" http://www.hotel-ma-rocade-pamiers.com",genre:"HÔTEL")
Lieu.create!(name:"Hôtel Première Classe ",city:" Pamiers ",description:" 30min ",phone:" 0 892 70 71 86 ",url:" http://www.premiereclasse.com/fr/hotels/premiere-classe-pamiers",genre:"HÔTEL")
